#document settings
title: DANA Laboratory
desc: "DANA Laboratory is an educational, equation based and open source project for process simulation"
url: http://vimalaad.github.io
repo_name: vimalaad.github.io
branch: master

#global settings, no need to change these
root_url: http://vimalaad.github.io
org_name: DANA-Laboratory
prose_url: http://prose.io

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false
